const CUSTOM_MODULE_NAME = "custom";
const CUSTOM_NEW_METHOD_NAME = "__new-catalog-method__";

export const CATALOG_CONFIG = {
  CUSTOM_MODULE_NAME,
  CUSTOM_NEW_METHOD_NAME,
  CUSTOM_NEW_METHOD_KEY: `${CUSTOM_MODULE_NAME}.${CUSTOM_NEW_METHOD_NAME}`,
} as const;
